name: Deploy Library API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Install dependencies
        run: npm install
      
      - name: Replace environment variables in HTML and JS
        run: |
          # Replace {{API_KEY}} and {{SHEET_ID}} placeholders with actual values
          sed -i 's|{{API_KEY}}|${{ secrets.API_KEY }}|' home/index.html
          sed -i 's|{{SHEET_ID}}|${{ secrets.SHEET_ID }}|' home/index.html
          sed -i 's|{{API_KEY}}|${{ secrets.API_KEY }}|' home/script.js
          sed -i 's|{{SHEET_ID}}|${{ secrets.SHEET_ID }}|' home/script.js

      - name: Deploy to GitHub Pages
        run: |
          npm run build
          git push origin gh-pages
